/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user — 404 if not in DB */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/frequent-crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the frequently seen crew for the authenticated user */
        get: operations["UsersController_getFrequentCrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert the authenticated Firebase user into the DB */
        post: operations["UsersController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organizations */
        get: operations["OrganizationsController_findAll"];
        put?: never;
        /** Create an organization (caller becomes owner) */
        post: operations["OrganizationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations the current user belongs to */
        get: operations["OrganizationsController_findMyOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization by id */
        get: operations["OrganizationsController_findOne"];
        put?: never;
        post?: never;
        /** Delete an organization (owner only) */
        delete: operations["OrganizationsController_remove"];
        options?: never;
        head?: never;
        /** Update an organization (owner/admin only) */
        patch: operations["OrganizationsController_update"];
        trace?: never;
    };
    "/organizations/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of an organization */
        get: operations["OrganizationsController_findMembers"];
        put?: never;
        /** Add a member to an organization (owner/admin only) */
        post: operations["OrganizationsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from an organization */
        delete: operations["OrganizationsController_removeMember"];
        options?: never;
        head?: never;
        /** Update a member role (owner/admin only) */
        patch: operations["OrganizationsController_updateMemberRole"];
        trace?: never;
    };
    "/drops/cron/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vercel Cron: transition drop statuses (requires CRON_SECRET) */
        post: operations["DropsController_runCronTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new drop */
        post: operations["DropsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's drops */
        get: operations["DropsController_getMyDrops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/activity/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's activity logs across all drops */
        get: operations["DropsController_getMyActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/join/{joinCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a drop by join code (public) */
        get: operations["DropsController_findByJoinCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a drop by id */
        get: operations["DropsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a drop (organiser only, active/ongoing status) */
        patch: operations["DropsController_update"];
        trace?: never;
    };
    "/drops/{id}/crew/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's crew status for a drop */
        get: operations["DropsController_getMyCrewStatus"];
        put?: never;
        post?: never;
        /** Leave a drop */
        delete: operations["DropsController_leaveDrop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew/me/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark yourself in or out for a drop (active crew members only) */
        patch: operations["DropsController_updatePresence"];
        trace?: never;
    };
    "/drops/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a drop */
        post: operations["DropsController_joinDrop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all crew members for a drop (organiser only) */
        get: operations["DropsController_getDropCrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew/{userId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a pending join request (organiser only) */
        patch: operations["DropsController_approvePendingMember"];
        trace?: never;
    };
    "/drops/{id}/crew/{userId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a pending join request (organiser only) */
        patch: operations["DropsController_rejectPendingMember"];
        trace?: never;
    };
    "/drops/{id}/crew/{userId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Remove an active crew member (organiser only) */
        patch: operations["DropsController_removeCrewMember"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatar?: string;
            role: string;
            isEmailVerified: boolean;
            /** Format: date-time */
            emailVerifiedAt?: string;
            /** Format: date-time */
            emailVerificationSentAt?: string;
            googleId?: string;
            firebaseUid?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Gender of the user
             * @enum {string}
             */
            gender?: "male" | "female" | "other";
            /** Format: date-time */
            birthday?: string;
            userHandle?: string;
            phone?: string;
            /** @description Whether the user has accepted the Terms & Conditions */
            termsAccepted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when Terms & Conditions were accepted
             */
            termsAcceptedAt?: string;
            /** @description Whether the user has accepted the Privacy Policy */
            privacyPolicyAccepted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when Privacy Policy was accepted
             */
            privacyPolicyAcceptedAt?: string;
        };
        UserProfileDto: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatar?: string;
            /** @enum {string} */
            role: "admin" | "photographer" | "participant";
            phone?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            userHandle?: string;
            isEmailVerified: boolean;
            isActive: boolean;
            /** @description Number of drops created by this user */
            dropCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FrequentCrewDto: {
            id: string;
            firstName: string;
            lastName: string;
            avatar?: string;
            userHandle?: string;
            /** Format: date-time */
            createdAt: string;
            frequencyCount: number;
        };
        SyncUserDto: {
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
        };
        CreateUserDto: {
            /** @example user@example.com */
            email: string;
            /** @example Jane */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example firebase-uid-123 */
            firebaseUid?: string;
            /** @example https://example.com/avatar.jpg */
            avatar?: string;
            /**
             * @default participant
             * @enum {string}
             */
            role: "admin" | "photographer" | "participant";
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /**
             * Format: date-time
             * @example 1990-01-01
             */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @example +639123456789 */
            phone?: string;
        };
        UpdateUserDto: {
            /** @example user@example.com */
            email?: string;
            /** @example Jane */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @example firebase-uid-123 */
            firebaseUid?: string;
            /** @example https://example.com/avatar.jpg */
            avatar?: string;
            /**
             * @default participant
             * @enum {string}
             */
            role: "admin" | "photographer" | "participant";
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /**
             * Format: date-time
             * @example 1990-01-01
             */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @example +639123456789 */
            phone?: string;
        };
        Organization: {
            id: string;
            name: string;
            slug?: string;
            logoUrl?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrganizationMember: {
            id: string;
            organizationId: string;
            userId: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            /** Format: date-time */
            joinedAt: string;
        };
        CreateOrganizationDto: {
            /** @example Acme Corp */
            name: string;
            /** @example acme-corp */
            slug?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
        };
        UpdateOrganizationDto: {
            /** @example Acme Corp */
            name?: string;
            /** @example acme-corp */
            slug?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
        };
        AddMemberDto: {
            userId: string;
            /**
             * @default member
             * @enum {string}
             */
            role: "owner" | "admin" | "member";
        };
        CreateDropDto: {
            /** @example Beach Sunset Shoot */
            name: string;
            /** @example 2026-05-10T18:00:00.000Z */
            scheduledAt: string;
            /** @example Sunset Beach, Manila */
            location: string;
            /** @example 20 */
            expectedHeadcount?: number;
            /** @example false */
            isLocked?: boolean;
        };
        Drop: {
            id: string;
            name: string;
            /** Format: date-time */
            scheduledAt: string;
            location: string;
            expectedHeadcount?: number;
            /** @enum {string} */
            status: "active" | "ongoing" | "completed";
            joinCode: string;
            shareUrl: string;
            /** @default false */
            isLocked: boolean;
            organiserId: string;
            organiser: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DropActivityLog: {
            id: string;
            dropId: string;
            userId: string;
            user: components["schemas"]["User"];
            action: string;
            changedFields?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
        };
        JoinDropResponseDto: {
            id: string;
            dropId: string;
            userId: string;
            /** @enum {string} */
            status: "in" | "pending" | "rejected" | "removed";
            /** @default false */
            isPresent: boolean;
            /** Format: date-time */
            joinedAt: string;
        };
        UpdatePresenceDto: {
            /** @description Whether the crew member is marking themselves as present */
            isPresent: boolean;
        };
        UpdateDropDto: {
            /** @example Golden Hour Shoot */
            name?: string;
            /** @example 2026-05-15T18:00:00.000Z */
            scheduledAt?: string;
            /** @example Rizal Park, Manila */
            location?: string;
            /** @description Lock the drop so new joiners require approval */
            isLocked?: boolean;
            /**
             * @description Manually override the drop status
             * @enum {string}
             */
            status?: "active" | "ongoing" | "completed";
        };
        CrewMemberUserDto: {
            id: string;
            firstName: string;
            lastName: string;
            avatar?: string;
        };
        CrewMemberDto: {
            id: string;
            dropId: string;
            userId: string;
            /** @enum {string} */
            status: "in" | "pending" | "rejected" | "removed";
            /** @default false */
            isPresent: boolean;
            /** Format: date-time */
            joinedAt: string;
            user: components["schemas"]["CrewMemberUserDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getFrequentCrew: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequentCrewDto"][];
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    OrganizationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    OrganizationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    OrganizationsController_findMyOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
        };
    };
    OrganizationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Organization not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient organization permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Insufficient organization permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_findMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
        };
    };
    OrganizationsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"];
                };
            };
            /** @description User is already a member. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_runCronTransition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transitions applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDropDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
        };
    };
    DropsController_getMyDrops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"][];
                };
            };
        };
    };
    DropsController_getMyActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropActivityLog"][];
                };
            };
        };
    };
    DropsController_findByJoinCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                joinCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDropDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description Drop is completed and cannot be edited. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can edit this drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_getMyCrewStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinDropResponseDto"];
                };
            };
            /** @description Not a crew member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_leaveDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully left the drop. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Organiser cannot leave their own drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew membership not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_updatePresence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePresenceDto"];
            };
        };
        responses: {
            /** @description Presence updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an active crew member. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a crew member of this drop. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_joinDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinDropResponseDto"];
                };
            };
            /** @description Drop is completed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Organiser cannot join their own drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already joined this drop. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_getDropCrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrewMemberDto"][];
                };
            };
            /** @description Only the organiser can view the crew list. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_approvePendingMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Join request approved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not pending approval. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can approve join requests. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_rejectPendingMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Join request rejected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not pending approval. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can reject join requests. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_removeCrewMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Crew member removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not an active crew member. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can remove crew members. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
