/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user — 404 if not in DB */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert the authenticated Firebase user into the DB */
        post: operations["UsersController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organizations */
        get: operations["OrganizationsController_findAll"];
        put?: never;
        /** Create an organization (caller becomes owner) */
        post: operations["OrganizationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations the current user belongs to */
        get: operations["OrganizationsController_findMyOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization by id */
        get: operations["OrganizationsController_findOne"];
        put?: never;
        post?: never;
        /** Delete an organization (owner only) */
        delete: operations["OrganizationsController_remove"];
        options?: never;
        head?: never;
        /** Update an organization (owner/admin only) */
        patch: operations["OrganizationsController_update"];
        trace?: never;
    };
    "/organizations/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of an organization */
        get: operations["OrganizationsController_findMembers"];
        put?: never;
        /** Add a member to an organization (owner/admin only) */
        post: operations["OrganizationsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from an organization */
        delete: operations["OrganizationsController_removeMember"];
        options?: never;
        head?: never;
        /** Update a member role (owner/admin only) */
        patch: operations["OrganizationsController_updateMemberRole"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatar?: string;
            role: string;
            isEmailVerified: boolean;
            /** Format: date-time */
            emailVerifiedAt?: string;
            /** Format: date-time */
            emailVerificationSentAt?: string;
            googleId?: string;
            firebaseUid?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Gender of the user
             * @enum {string}
             */
            gender?: "male" | "female" | "other";
            /** Format: date-time */
            birthday?: string;
            userHandle?: string;
            phone?: string;
            /** @description Whether the user has accepted the Terms & Conditions */
            termsAccepted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when Terms & Conditions were accepted
             */
            termsAcceptedAt?: string;
            /** @description Whether the user has accepted the Privacy Policy */
            privacyPolicyAccepted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when Privacy Policy was accepted
             */
            privacyPolicyAcceptedAt?: string;
        };
        UserProfileDto: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatar?: string;
            /** @enum {string} */
            role: "admin" | "photographer" | "participant";
            phone?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            userHandle?: string;
            isEmailVerified: boolean;
            isActive: boolean;
            /** @description Number of drops created by this user */
            dropCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SyncUserDto: {
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
        };
        CreateUserDto: {
            /** @example user@example.com */
            email: string;
            /** @example Jane */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example firebase-uid-123 */
            firebaseUid?: string;
            /** @example https://example.com/avatar.jpg */
            avatar?: string;
            /**
             * @default participant
             * @enum {string}
             */
            role: "admin" | "photographer" | "participant";
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /**
             * Format: date-time
             * @example 1990-01-01
             */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @example +639123456789 */
            phone?: string;
        };
        UpdateUserDto: {
            /** @example user@example.com */
            email?: string;
            /** @example Jane */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @example firebase-uid-123 */
            firebaseUid?: string;
            /** @example https://example.com/avatar.jpg */
            avatar?: string;
            /**
             * @default participant
             * @enum {string}
             */
            role: "admin" | "photographer" | "participant";
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /**
             * Format: date-time
             * @example 1990-01-01
             */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @example +639123456789 */
            phone?: string;
        };
        Organization: {
            id: string;
            name: string;
            slug?: string;
            logoUrl?: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrganizationMember: {
            id: string;
            organizationId: string;
            userId: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
            /** Format: date-time */
            joinedAt: string;
        };
        CreateOrganizationDto: {
            /** @example Acme Corp */
            name: string;
            /** @example acme-corp */
            slug?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
        };
        UpdateOrganizationDto: {
            /** @example Acme Corp */
            name?: string;
            /** @example acme-corp */
            slug?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
        };
        AddMemberDto: {
            userId: string;
            /**
             * @default member
             * @enum {string}
             */
            role: "owner" | "admin" | "member";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    OrganizationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    OrganizationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    OrganizationsController_findMyOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
        };
    };
    OrganizationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Organization not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient organization permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Insufficient organization permissions. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_findMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
        };
    };
    OrganizationsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"];
                };
            };
            /** @description User is already a member. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
