/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user — 404 if not in DB */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/frequent-crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the frequently seen crew for the authenticated user */
        get: operations["UsersController_getFrequentCrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/auth-provider-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check whether an email already belongs to an existing auth provider */
        post: operations["UsersController_checkAuthProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["UsersController_remove"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert the authenticated user profile into the DB */
        post: operations["UsersController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/avatar/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create signed upload session for profile avatar */
        post: operations["UsersController_createAvatarUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/avatar/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize signed avatar upload and replace previous avatar */
        post: operations["UsersController_completeAvatarUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/cron/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vercel Cron: transition drop statuses (requires CRON_SECRET) */
        post: operations["DropsController_runCronTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get drops for the discover page (public-safe fields only) */
        get: operations["DropsController_discover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new drop */
        post: operations["DropsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's drops */
        get: operations["DropsController_getMyDrops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/activity/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's activity logs across all drops */
        get: operations["DropsController_getMyActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/join/{joinCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a drop by join code */
        get: operations["DropsController_findByJoinCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a drop by id (public access for public drops) */
        get: operations["DropsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a drop (organiser only) */
        delete: operations["DropsController_delete"];
        options?: never;
        head?: never;
        /** Edit a drop (organiser only, active/ongoing status) */
        patch: operations["DropsController_update"];
        trace?: never;
    };
    "/drops/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated activity logs for a drop */
        get: operations["DropsController_getActivityLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's crew status for a drop */
        get: operations["DropsController_getMyCrewStatus"];
        put?: never;
        post?: never;
        /** Leave a drop */
        delete: operations["DropsController_leaveDrop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew/me/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark yourself in or out for a drop (active crew members only) */
        patch: operations["DropsController_updatePresence"];
        trace?: never;
    };
    "/drops/{id}/invite/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a user to a drop (organiser only) */
        post: operations["DropsController_inviteToDrop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a drop */
        post: operations["DropsController_joinDrop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all crew members for a drop (organiser only) */
        get: operations["DropsController_getDropCrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/crew/{userId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a pending join request (organiser only) */
        patch: operations["DropsController_approvePendingMember"];
        trace?: never;
    };
    "/drops/{id}/crew/{userId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a pending join request (organiser only) */
        patch: operations["DropsController_rejectPendingMember"];
        trace?: never;
    };
    "/drops/{id}/crew/{userId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Remove an active crew member (organiser only) */
        patch: operations["DropsController_removeCrewMember"];
        trace?: never;
    };
    "/drops/{id}/cover-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload or replace the drop cover photo (organiser only, max 5 MB, JPG/PNG) */
        post: operations["DropsController_uploadCoverPhoto"];
        /** Delete the drop cover photo (organiser only) */
        delete: operations["DropsController_deleteCoverPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all photos for a drop (paginated) */
        get: operations["DropsController_getPhotos"];
        put?: never;
        /** Upload a photo to the drop roll (crew members only) */
        post: operations["DropsController_uploadPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/photos/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a signed upload session for a drop roll photo */
        post: operations["DropsController_createPhotoUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/photos/{photoId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize a signed upload and return the photo payload */
        post: operations["DropsController_completePhotoUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single photo detail (includes base64 if available) */
        get: operations["DropsController_getPhotoDetail"];
        put?: never;
        post?: never;
        /** Delete a photo from the roll (owner or organiser only) */
        delete: operations["DropsController_deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drops/{id}/photos/{photoId}/feature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Feature a photo from the roll (organiser only) */
        patch: operations["DropsController_featurePhoto"];
        trace?: never;
    };
    "/drops/{id}/spark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Spark a drop (hype) */
        post: operations["DropsController_sparkDrop"];
        /** Unspark a drop */
        delete: operations["DropsController_unsparkDrop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send password reset email */
        post: operations["AuthEmailController_sendResetEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend email verification */
        post: operations["AuthEmailController_sendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            email: string;
            /** @enum {string} */
            authProvider: "password" | "google";
            firstName: string;
            lastName: string;
            avatar?: string;
            avatarStoragePath?: Record<string, never>;
            role: string;
            isEmailVerified: boolean;
            /** Format: date-time */
            emailVerifiedAt?: string;
            /** Format: date-time */
            emailVerificationSentAt?: string;
            /** Format: date-time */
            passwordResetSentAt?: string;
            isActive: boolean;
            /** @description Whether the user has completed onboarding */
            onboardingCompleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description Gender of the user
             * @enum {string}
             */
            gender?: "male" | "female" | "other";
            /** Format: date-time */
            birthday?: string;
            userHandle?: string;
            phone?: string;
            /** @description Whether the user has accepted the Terms & Conditions */
            termsAccepted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when Terms & Conditions were accepted
             */
            termsAcceptedAt?: string;
            /** @description Whether the user has accepted the Privacy Policy */
            privacyPolicyAccepted: boolean;
            /**
             * Format: date-time
             * @description Timestamp when Privacy Policy was accepted
             */
            privacyPolicyAcceptedAt?: string;
        };
        UserProfileDto: {
            id: string;
            email: string;
            /** @enum {string} */
            authProvider: "password" | "google";
            firstName: string;
            lastName: string;
            avatar?: string;
            /** @enum {string} */
            role: "admin" | "participant";
            phone?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /**
             * Format: date-time
             * @example 1990-01-01
             */
            birthday?: string;
            userHandle?: string;
            isEmailVerified: boolean;
            isActive: boolean;
            /** @description Number of drops created by this user */
            dropCount: number;
            /** @description Total unique crew members reached across all drops */
            crewReached: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FrequentCrewDto: {
            id: string;
            firstName: string;
            lastName: string;
            avatar?: string;
            userHandle?: string;
            /** Format: date-time */
            createdAt: string;
            frequencyCount: number;
        };
        CheckAuthProviderDto: {
            /** @example user@example.com */
            email: string;
        };
        SyncUserDto: {
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /** @example 1990-01-01 */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @enum {string} */
            authMode?: "login" | "signup";
            /** @enum {string} */
            authProvider?: "password" | "google";
            /** @example user@example.com */
            email?: string;
            /** @example true */
            termsAccepted?: boolean;
            /** @example 2026-05-04T10:42:00.000Z */
            termsAcceptedAt?: string;
            /** @example true */
            privacyPolicyAccepted?: boolean;
            /** @example 2026-05-04T10:42:00.000Z */
            privacyPolicyAcceptedAt?: string;
        };
        CreateUserDto: {
            /** @example user@example.com */
            email: string;
            /**
             * @default password
             * @enum {string}
             */
            authProvider: "password" | "google";
            /** @example Jane */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example https://example.com/avatar.jpg */
            avatar?: string;
            /**
             * @default participant
             * @enum {string}
             */
            role: "admin" | "participant";
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /** @example 1990-01-01 */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @example +639123456789 */
            phone?: string;
            /** @default false */
            termsAccepted: boolean;
            /** Format: date-time */
            termsAcceptedAt?: string;
            /** @default false */
            privacyPolicyAccepted: boolean;
            /** Format: date-time */
            privacyPolicyAcceptedAt?: string;
        };
        UpdateUserDto: {
            /** @example Jane */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @example https://example.com/avatar.jpg */
            avatar?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
            /** @example 1990-01-01 */
            birthday?: string;
            /** @example jane_doe */
            userHandle?: string;
            /** @example +639123456789 */
            phone?: string;
            /** @default false */
            termsAccepted: boolean;
            /** Format: date-time */
            termsAcceptedAt?: string;
            /** @default false */
            privacyPolicyAccepted: boolean;
            /** Format: date-time */
            privacyPolicyAcceptedAt?: string;
        };
        CreateAvatarUploadDto: {
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/jpg" | "image/png";
            /** @description Original file size in bytes */
            sizeBytes: number;
            width?: number;
            height?: number;
        };
        AvatarUploadSessionDto: {
            userId: string;
            storagePath: string;
            uploadToken: string;
        };
        DropOrganiserPublicDto: {
            id: string;
            firstName: string;
            lastName: string;
            avatar?: Record<string, never> | null;
            userHandle?: Record<string, never> | null;
        };
        DropDiscoverSummaryDto: {
            id: string;
            name: string;
            /** Format: date-time */
            scheduledAt: string;
            location: string;
            expectedHeadcount?: number | null;
            overview?: Record<string, never> | null;
            coverPhoto?: Record<string, never> | null;
            /** @enum {string} */
            status: "active" | "ongoing" | "completed";
            /** @enum {string|null} */
            category?: "hangout" | "party" | null;
            /** @description Minimum age when category is party; null if unrestricted. */
            minimumAge?: number | null;
            isPublic: boolean;
            isLocked: boolean;
            organiserId: string;
            organiser: components["schemas"]["DropOrganiserPublicDto"];
            /** @description Total spark count (no user identifiers). */
            sparkCount: number;
            /** @description Included when the request is authenticated: whether this user has sparked the drop. */
            sparkedByViewer?: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DiscoverDropsPaginatedDto: {
            data: components["schemas"]["DropDiscoverSummaryDto"][];
            total: number;
            page: number;
            totalPages: number;
        };
        DiscoverDropsResponseDto: {
            /** @description Featured drop when available. */
            featured?: components["schemas"]["DropDiscoverSummaryDto"] | null;
            recentChiefsDrops: components["schemas"]["DropDiscoverSummaryDto"][];
            allPublic: components["schemas"]["DiscoverDropsPaginatedDto"];
        };
        CreateDropDto: {
            /** @example Beach Sunset Shoot */
            name: string;
            /** @example 2026-05-10T18:00:00.000Z */
            scheduledAt: string;
            /** @example Sunset Beach, Manila */
            location: string;
            /** @example 20 */
            expectedHeadcount?: number;
            /** @example This is a fun beach shoot */
            overview?: string;
            /** @example false */
            isLocked?: boolean;
            /** @example true */
            isPublic?: boolean;
            /**
             * @example hangout
             * @enum {string}
             */
            category?: "hangout" | "party";
            /** @description Minimum attendee age (≥). Only stored when category is party. */
            minimumAge?: number | null;
            /** @example uuid-string */
            idempotencyKey?: string;
            /** @description Optional JPG/PNG cover as data URL; max 5MB decoded size. */
            coverPhotoBase64?: string;
        };
        DropSpark: {
            id: string;
            dropId: string;
            userId: string;
            /** Format: date-time */
            createdAt: string;
        };
        Drop: {
            id: string;
            name: string;
            /** Format: date-time */
            scheduledAt: string;
            location: string;
            expectedHeadcount?: number | null;
            overview?: Record<string, never> | null;
            coverPhoto?: Record<string, never> | null;
            /** @enum {string} */
            status: "active" | "ongoing" | "completed";
            /** @enum {string} */
            category?: "hangout" | "party";
            minimumAge?: number | null;
            joinCode: string;
            shareUrl: string;
            /** @default true */
            isPublic: boolean;
            /** @default false */
            isLocked: boolean;
            idempotencyKey?: Record<string, never> | null;
            organiserId: string;
            organiser: components["schemas"]["User"];
            sparks: components["schemas"]["DropSpark"][];
            sparkCount?: number;
            sparkedByViewer?: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DropActivityLog: {
            id: string;
            dropId: string;
            userId: string;
            user: components["schemas"]["User"];
            action: string;
            changedFields?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
        };
        CrewMemberUserDto: {
            id: string;
            firstName: string;
            lastName: string;
            avatar?: string;
        };
        DropActivityLogPublicDto: {
            id: string;
            dropId: string;
            userId: string;
            user: components["schemas"]["CrewMemberUserDto"];
            action: string;
            /** @description Whitelisted changed field names only; values are always true. */
            changedFields?: {
                [key: string]: boolean;
            };
            /** Format: date-time */
            createdAt: string;
        };
        ActivityLogsPageDto: {
            data: components["schemas"]["DropActivityLogPublicDto"][];
            total: number;
            page: number;
            totalPages: number;
        };
        JoinDropResponseDto: {
            id: string;
            dropId: string;
            userId: string;
            /** @enum {string} */
            status: "in" | "pending" | "rejected" | "removed" | "invited";
            /** @default false */
            isPresent: boolean;
            /** Format: date-time */
            joinedAt: string;
        };
        UpdatePresenceDto: {
            /** @description Whether the crew member is marking themselves as present */
            isPresent: boolean;
        };
        UpdateDropDto: {
            /** @example Golden Hour Shoot */
            name?: string;
            /** @example 2026-05-15T18:00:00.000Z */
            scheduledAt?: string;
            /** @example Rizal Park, Manila */
            location?: string;
            /** @example 20 */
            expectedHeadcount?: number | null;
            /** @example Updated overview */
            overview?: string;
            /** @description Lock the drop so new joiners require approval */
            isLocked?: boolean;
            /** @description Set visibility to public or private */
            isPublic?: boolean;
            /**
             * @description Manually override the drop status
             * @enum {string}
             */
            status?: "active" | "ongoing" | "completed";
            /**
             * @example hangout
             * @enum {string}
             */
            category?: "hangout" | "party";
            /** @description Minimum attendee age for party drops; null clears the restriction. */
            minimumAge?: number | null;
        };
        CrewMemberDto: {
            id: string;
            dropId: string;
            userId: string;
            /** @enum {string} */
            memberRole: "chief" | "crew" | "co_chief";
            /** @enum {string} */
            status: "in" | "pending" | "rejected" | "removed" | "invited";
            /** @default false */
            isPresent: boolean;
            /** Format: date-time */
            joinedAt: string;
            user: components["schemas"]["CrewMemberUserDto"];
        };
        DropPhoto: {
            id: string;
            dropId: string;
            userId: string;
            url?: Record<string, never> | null;
            storagePath?: Record<string, never> | null;
            mimeType?: Record<string, never> | null;
            sizeBytes?: Record<string, never> | null;
            width?: Record<string, never> | null;
            height?: Record<string, never> | null;
            base64?: Record<string, never> | null;
            /** @default false */
            isFeatured: boolean;
            user: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePhotoUploadDto: {
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/jpg" | "image/png";
            /** @description Original file size in bytes */
            sizeBytes: number;
            /** @description Client image width in pixels */
            width?: number;
            /** @description Client image height in pixels */
            height?: number;
        };
        PhotoUploadSessionDto: {
            photoId: string;
            storagePath: string;
            uploadToken: string;
        };
        DropPhotoPublicDto: {
            id: string;
            dropId: string;
            userId: string;
            url?: Record<string, never> | null;
            /** @description Deprecated: image payloads are no longer returned in API responses. */
            base64?: Record<string, never> | null;
            isFeatured: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["CrewMemberUserDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileDto"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getFrequentCrew: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequentCrewDto"][];
                };
            };
        };
    };
    UsersController_checkAuthProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAuthProviderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    UsersController_createAvatarUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvatarUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUploadSessionDto"];
                };
            };
        };
    };
    UsersController_completeAvatarUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    DropsController_runCronTransition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transitions applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_discover: {
        parameters: {
            query: {
                page: number;
                limit: number;
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverDropsResponseDto"];
                };
            };
        };
    };
    DropsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDropDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
        };
    };
    DropsController_getMyDrops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"][];
                };
            };
        };
    };
    DropsController_getMyActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropActivityLog"][];
                };
            };
        };
    };
    DropsController_findByJoinCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                joinCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drop deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can delete this drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDropDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description Drop is completed and cannot be edited. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can edit this drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_getActivityLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogsPageDto"];
                };
            };
            /** @description Drop not found or no access. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_getMyCrewStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinDropResponseDto"];
                };
            };
            /** @description Not a crew member. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_leaveDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully left the drop. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Organiser cannot leave their own drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew membership not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_updatePresence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePresenceDto"];
            };
        };
        responses: {
            /** @description Presence updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an active crew member. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a crew member of this drop. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_inviteToDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User invited successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_joinDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinDropResponseDto"];
                };
            };
            /** @description Drop is completed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Organiser cannot join their own drop, age requirement not met, or birthday missing for an age-restricted drop. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already joined this drop. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_getDropCrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrewMemberDto"][];
                };
            };
            /** @description Only the organiser can view the crew list. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_approvePendingMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Join request approved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not pending approval. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can approve join requests. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_rejectPendingMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Join request rejected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not pending approval. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can reject join requests. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_removeCrewMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Crew member removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not an active crew member. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can remove crew members. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop or crew member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_uploadCoverPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drop"];
                };
            };
            /** @description No file provided or unsupported format. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can update the cover photo. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_deleteCoverPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cover photo deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Only the organiser can delete the cover photo. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Drop not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_getPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropPhotoPublicDto"][];
                };
            };
        };
    };
    DropsController_uploadPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropPhoto"];
                };
            };
        };
    };
    DropsController_createPhotoUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhotoUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadSessionDto"];
                };
            };
        };
    };
    DropsController_completePhotoUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropPhotoPublicDto"];
                };
            };
        };
    };
    DropsController_getPhotoDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropPhotoPublicDto"];
                };
            };
        };
    };
    DropsController_deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_featurePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropPhoto"];
                };
            };
        };
    };
    DropsController_sparkDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dropped sparked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DropsController_unsparkDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dropped unsparked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthEmailController_sendResetEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthEmailController_sendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
